Repository fpgasystems/Coyote, pull requests merged in 2024-11, with the labels that each got.

#90 GitHub templates for PRs, issues etc.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#81 Added documentation to retrans_buffer and changed RDMA_sw for easier debugging
  examples_sw/apps/rdma_service/client/main.cpp
  examples_sw/apps/rdma_service/server/main.cpp
  hw/hdl/network/rdma/rdma_mux_retrans.sv
  hw/hdl/network/rdma/roce_stack.sv
Labels: documentation, bugfix

#87 Fixed flow_alveo.sh environment issue
  README.md
  util/find.py
  util/insmod_local.sh
  util/program_hacc_local.sh
  util/program_hacc_remote.sh
Labels: enhancement

#86 Bugfix for the retrans-issue that stopped RDMA-writes at 8k: We now h…
  hw/hdl/network/rdma/rdma_mux_retrans.sv
  hw/hdl/network/rdma/roce_stack.sv
Labels: bugfix
